version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          max_command_length: 120
          filters: *filters
          exclude: "RC006, RC007"
      - shellcheck/check:
          filters: *filters
      - orb-tools/publish:
          orb_name: ft-circleci-orbs/cloudsmith-oidc
          vcs_type: << pipeline.project.type >>
          requires:
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
            - shellcheck/check
          # The context holds the CIRCLE_TOKEN for publishing
          context: circleci-orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          config_path: .circleci/test-deploy.yml
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: cloudsmith-oidc
          requires: [orb-tools/publish]
          filters: *filters
