version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  cloudsmith-oidc: ft-circleci-orbs/cloudsmith-oidc@1.0.0
  # The orb definition is intentionally not included here. It will be injected into the pipeline. Test
  #cloudsmith-oidc: {}

# Filter for tests
filters: &filters
  tags:
    only: /.*/

# Filter for publishing a release.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  test-authenticate_with_oidc:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - cloudsmith-oidc/authenticate_with_oidc
      - run:
          name: Assert environment variables have been set
          command: | 
            if [ -z $CLOUDSMITH_OIDC_TOKEN ]
            then
              echo "Test failed: CLOUDSMITH_OIDC_TOKEN has not been set."
              exit 1
            fi
            echo "All tests passed."

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - test-authenticate_with_oidc:
          filters: *filters
      # Pack the orb publishing for a new release.
      - orb-tools/pack:
          filters: *release-filters
      # Publishing the new release.
      - orb-tools/publish:
          filters: *release-filters
          orb_name: ft-circleci-orbs/cloudsmith-oidc
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
            - test-authenticate_with_oidc
          # The context holds the CIRCLE_TOKEN for publishing
          context: circleci-orb-publishing
